Temporary disabling windows builds due to linking errors
Something wrong with Rust and/or MinGW:
```
C:\Users\travis\build\katyo\fluidlite-rs\target\release\deps\libfluidlite_lib-22c0f1980c89368d.rlib(fluid_sys.c.obj):fluid_sys.c:(.text$fluid_default_log_function+0x13):
undefined reference to `__imp___acrt_iob_func'
```